micronaut:
  application:
    name: examples
  server:
    port: 8080
    cors:
      enabled: true
  #tag::oauth2[]
  security:
    enabled: true # <1>
    oauth2:
      enabled: true
      clients:
        cognito: # <2>
          client-secret: '${OAUTH_CLIENT_SECRET}' # <3>
          client-id: '${OAUTH_CLIENT_ID}' # <4>
          openid:
            issuer: '${OIDC_ISSUER_DOMAIN}/oauth2/${OIDC_ISSUER_AUTHSERVERID}' # <5>
    token:
      jwt:
        enabled: true # <6>
        cookie:
          enabled: true # <7>
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
    endpoints:
      logout:
        enabled: true # <8>
        get-allowed: true # <9>
#end::oauth2[]
